import {
  Controller,
  Get,
  Post,
  Body,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ReadingsService } from './readings.service';
import { CreateReadingDto } from './dto/create-reading.dto';

@Controller('readings')
export class ReadingsController {
  constructor(private readonly readingsService: ReadingsService) {}

  // POST /readings - To receive and store sensor data
  @Post()
  @HttpCode(HttpStatus.CREATED) // Return 201 Created
  create(@Body() createReadingDto: CreateReadingDto) {
    return this.readingsService.create(createReadingDto);
  }

  // GET /readings/latest - To retrieve the last recorded sensor value
  @Get('latest')
  findLatest() {
    return this.readingsService.findLatest();
  }

  // You can remove the default findAll, findOne, update, and remove methods
  // generated by the CLI, as they are not explicitly required by the task.
}
